server:
  port: 8080

  servlet:
    context-path: /qbrainx-Mcq

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Security
    username: postgres
    password: admin@1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create


    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

liquibase:
  enabled: true

springdoc:
  group-configs:
    - group: qbrainx-website
      packagesToScan:
        - "com.mytry.crud"
  swagger-ui:
    path: /qbrainx-1336586310L-swagger-ui.html
  api-docs:
    path: /v3/qbrainx-1336586310L-api-docs